
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 82
#define YY_END_OF_BUFFER 83
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[373] =
    {   0,
        5,    5,    0,    0,   83,   79,    5,    5,   74,   81,
       71,   72,   81,   76,   71,   71,   75,   68,   73,   67,
       73,   72,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   75,
       75,   77,   75,   72,    2,    2,    5,    0,    5,    5,
       48,   79,   79,    1,   68,   68,   68,    0,   49,    0,
        0,   80,   46,   51,    0,   69,    0,    0,   68,    0,
       52,   55,   64,   63,   58,   61,   65,   54,   47,   53,
       66,   56,   77,   77,   77,   77,   15,   77,   77,   21,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,

       77,   77,   77,   41,   77,   77,   77,   77,   57,   77,
        0,   50,    3,    4,   68,   68,   68,   68,   68,   68,
        0,    0,    0,    0,   69,    0,    0,   69,    0,   68,
        0,    0,   60,   62,   59,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       27,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   39,   77,   77,   77,   77,   77,   77,   77,
       78,    0,    3,   68,   68,   68,   68,   68,    0,    0,
        0,   69,   69,   69,   69,    0,    0,    0,   77,   77,
        9,   77,   77,   77,   77,   77,   77,   77,   77,   77,

       77,   77,   77,   77,   77,   77,   77,   77,   30,   77,
       77,   33,   34,   35,   77,   77,   38,   77,   42,   77,
       77,   77,   77,   77,    0,   69,   69,   69,   69,    0,
        0,    0,   70,    6,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   29,   31,   77,   77,   77,   77,   77,   43,   44,
       77,   77,   69,   69,    0,    0,   70,   70,    0,    0,
        0,   70,   77,   10,   77,   77,   77,   77,   77,   77,
       77,   77,   20,   22,   77,   77,   77,   77,   77,   77,
       77,   77,   40,    7,   77,    7,   70,    0,   70,   70,

        0,   70,    0,    0,    0,    0,   77,   77,   77,   77,
       77,   16,   77,   18,   77,   77,   77,   77,   26,   28,
       77,   77,   77,   77,   70,   70,   70,    0,    0,    0,
        0,    0,    0,    8,   11,   12,   77,   77,   17,   19,
       77,   24,   77,   32,   77,   37,   77,   70,   70,    0,
        0,    0,    0,    0,    0,    0,   77,   14,   77,   25,
       36,   45,   70,    0,    0,    0,    0,   13,   23,    0,
        0,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    5,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,    1,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   37,   49,   50,   51,
       52,   53,   54,   55,   56,    1,   57,   58,   59,   60,

       61,   62,   63,   64,   65,   66,   37,   67,   68,   69,
       70,   71,   72,   73,   74,   75,   76,   77,   37,   78,
       79,   80,   81,   82,   83,   84,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[85] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    5,    6,    7,    7,    7,    8,
        1,    1,    1,    1,    1,    1,    9,    9,    9,    9,
        9,    9,   10,   11,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,    1,    1,    1,    1,   12,   13,   13,    9,    9,
        9,   13,   10,   11,   10,   10,   10,   10,   11,   10,
       10,   10,   11,   10,   11,   10,   11,   10,   10,   10,
        1,    6,    1,    1
    } ;

static const flex_int16_t yy_base[390] =
    {   0,
        0,    0,  513,  509,  512, 1289,   83,   84,  483,   84,
     1289,  497,   85, 1289,  438,  412,   89,   95,  417,  110,
     1289, 1289,   47,    0,   70,   64,  109,   97,   72,  103,
      102,  111,   77,  120,  108,  139,  144,  103,  123, 1289,
      410,  154, 1289,  342, 1289,  407,  126,  390,  102,  183,
     1289,    0, 1289, 1289,  195,  203,  211,  256, 1289,  183,
      215, 1289, 1289, 1289,  218,  240,  229,  222,  285,  311,
     1289, 1289, 1289,  376, 1289,  343, 1289,  340, 1289, 1289,
     1289, 1289,    0,  121,  237,  130,  229,  145,  263,  265,
      160,  195,  267,  211,  283,  229,  207,  248,  226,  275,

      286,  293,  285,  289,  291,  289,  297,  290, 1289,  296,
      267, 1289,  195,    0,  356,  362,  373,  379,  436,  396,
      184,  400,  402,  326,  427,    0,  409,  457,  269,  464,
      202,  270, 1289, 1289, 1289,  312,  322,  458,  338,  425,
      339,  296,  343,  376,  375,  382,  385,  387,  391,  414,
        0,  421,  429,  452,  441,  461,  460,  475,  476,  465,
      473,  470,    0,  463,  469,  484,  472,  473,  485,  495,
     1289,  241,  383,  539,  255,    0,    0,  211,  543,  245,
      600,  558,  566,  574,  613,    0,  200,  624,  474,  506,
        0,  486,  511,  484,  499,  531,  538,  531,  541,  581,

      590,  595,  592,  593,  604,  616,  613,  606,    0,  630,
      605,    0,    0,    0,  629,  616,    0,  634,    0,  624,
      620,  627,  635,  630,  430,    0,  188,  685,  692,  701,
      705,  709,  725,    0,  640,  659,  662,  685,  690,  691,
      686,  685,  688,  707,  697,  705,  712,  717,  720,  707,
      711,    0,    0,  711,  721,  730,  715,  723,    0,    0,
      740,  729,    0,  184,  755,  777,  785,  796,    0,  758,
      807,  813,  747,    0,  775,  762,  769,  763,  776,  790,
      796,  794,    0,    0,  788,  789,  805,  801,  803,  818,
      802,  808,    0,    0,  810,    0,  863,    0,  874,  880,

      891,  897,  908,    0,  869,  919,  827,  817,  860,  872,
      892,    0,  877,    0,  881,  882,  904,  901,    0,    0,
      898,  897,  913,  913,  948,  968,  144,  974,  985,  993,
        0,  997, 1002,    0,    0,    0,  914,  904,    0,    0,
      911,    0,  955,    0,  955,    0,  952,  129,  104,    0,
       85, 1022, 1033, 1040, 1051,    0,  954,    0,  919,    0,
        0,    0,   73,    0,   41, 1057, 1073,    0,    0,    0,
       18, 1289, 1134, 1147, 1154, 1163, 1176, 1183, 1195, 1206,
     1213, 1220, 1233, 1240, 1247, 1254, 1261, 1268, 1275
    } ;

static const flex_int16_t yy_def[390] =
    {   0,
      372,    1,  373,  373,  372,  372,  372,  372,  372,  372,
      372,  372,  374,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  372,
      372,  375,  372,  376,  372,  372,  372,  372,  372,  372,
      372,  377,  372,  372,  372,  372,  372,  378,  372,  374,
      379,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,

      375,  375,  375,  375,  375,  375,  375,  375,  372,  375,
      376,  372,  372,  377,  372,  372,  372,  372,  378,  380,
      372,  374,  374,  381,  372,  382,  372,  372,  372,  372,
      380,  372,  372,  372,  372,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      372,  372,  372,  380,  174,  174,  174,  174,  374,  374,
      383,  372,  372,  382,  372,  384,  372,  372,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,

      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  374,  184,  184,  372,  384,  372,
      372,  372,  372,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  229,  229,  372,  372,  372,  372,  385,  372,
      372,  372,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  372,  386,  372,  372,

      372,  385,  372,  387,  372,  372,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  372,  386,  302,  372,  387,  372,
      388,  372,  372,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  326,  302,  329,
      329,  372,  372,  388,  372,  389,  375,  375,  375,  375,
      375,  375,  326,  354,  354,  372,  389,  375,  375,  367,
      367,    0,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372
    } ;

static const flex_int16_t yy_nxt[1374] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   14,
       15,   11,   14,   16,   17,   11,   18,   18,   18,   18,
       14,   14,   19,   20,   21,   22,   23,   24,   25,   26,
       27,   28,   24,   29,   24,   24,   24,   30,   31,   32,
       33,   34,   24,   35,   36,   37,   38,   39,   24,   24,
       24,   40,   40,   40,   41,   24,   23,   24,   25,   26,
       27,   28,   24,   29,   24,   24,   30,   31,   32,   33,
       34,   24,   35,   36,   42,   38,   39,   24,   24,   24,
       43,   44,   43,   22,   47,   49,   50,   48,   52,   61,
       84,   53,   62,   65,   87,  187,   85,   54,   95,   67,

       55,   56,   57,   49,   50,   66,   66,   66,   66,   68,
       86,   69,   69,   69,   69,   72,   73,   58,  187,   84,
       74,   75,   99,   76,   87,   77,   85,   47,   95,   96,
       48,   93,   78,   79,   80,   81,   97,   98,  102,   86,
       53,   53,  107,   94,   88,   53,  100,   58,   89,  108,
      132,   99,   53,   90,   91,   70,   53,   92,   53,   96,
       53,   93,  132,  101,  136,  103,   97,   98,  102,  140,
      105,  107,   94,  104,   88,  143,  100,   89,  106,  108,
      105,  132,   90,   91,   49,   50,   92,   61,  106,  363,
       62,   82,  101,  136,  148,  103,  172,  173,  140,   67,

      105,  123,  123,  104,  349,  143,  372,   67,  106,   68,
      110,  115,  116,  116,   69,   67,  372,   68,  106,  115,
      117,  117,   69,  149,  148,   68,   65,  115,  118,  118,
       69,  121,  122,  123,  125,  125,  125,  156,   66,   66,
       66,   66,  172,  173,  127,  130,  130,  130,  124,   61,
      152,  126,   62,  149,   68,   70,  128,  128,  128,  128,
      141,  187,  131,   70,  137,  187,  138,  156,  155,  158,
      230,   70,  119,  119,  119,  120,  142,  157,  124,  152,
      139,  126,  120,  120,  120,  120,  120,  120,  132,   67,
      141,  144,  131,  146,  137,  150,  138,  155,  158,   68,

      129,   69,   69,   69,   69,  142,  151,  157,  145,  139,
      147,  153,  120,  120,  120,  120,  120,  120,  159,  162,
      160,  144,  164,  146,  163,  150,  161,  154,  165,  166,
      167,  168,  132,  169,  166,  151,  198,  145,  189,  147,
      188,  153,  181,  181,  181,   70,  187,  159,  171,  162,
      160,  164,  190,  135,  163,  161,  154,  165,  166,  167,
       67,  168,  169,  170,  193,  198,   67,  134,  189,  197,
       68,  199,  115,  115,  115,   69,   68,   67,  115,  118,
      118,   69,  190,   67,  172,  173,  133,   68,  132,  115,
      118,  118,   69,   68,  193,  115,  115,  115,   69,  197,

       67,  199,  200,   54,   61,  201,   61,   62,  202,   62,
       68,  113,  176,  176,  176,  176,   70,  179,  179,  180,
      180,  205,   70,  112,  109,  185,  185,  185,  203,  204,
       71,  127,  200,   70,   61,  201,   64,   62,  202,   70,
       67,   68,  186,  182,  182,  182,  183,  206,   63,  207,
       68,  205,  174,  174,  174,  174,  178,  203,  204,  208,
      194,  127,  120,  120,  120,  120,  120,  120,   67,  195,
      196,   68,  186,  128,  128,  128,  128,  206,   68,  207,
      115,  115,  115,   69,  191,  209,  212,  129,  192,  208,
      194,  210,  120,  120,  120,  120,  175,  120,  195,  196,

      211,  213,  214,   59,  215,  216,   51,  217,  218,  219,
      220,  372,  221,  222,  191,  209,  212,  129,  192,  223,
      210,  220,   46,  234,   70,  236,   46,  372,  372,  211,
      238,  213,  214,  215,  235,  216,  217,  218,  219,  237,
      220,  221,  222,   67,  239,  372,  372,   61,  372,  223,
       62,  224,  234,   68,  236,  176,  176,  176,  176,  238,
      180,  180,  127,  372,  235,  240,  241,  372,  242,  237,
      127,  372,   68,  239,  182,  182,  182,  183,  127,  372,
       68,  372,  183,  183,  183,  183,  372,  243,   68,  372,
      226,  226,  226,  226,  372,  240,  241,  242,  372,  178,

       60,   60,  372,   60,   61,   60,   60,   62,   60,   60,
       60,   60,   60,   60,   60,   60,  243,  127,  129,  244,
       60,   60,   60,   60,   60,   60,  129,   68,  231,  228,
      228,  228,  183,  245,  227,  232,  246,  232,  247,  248,
      233,  233,  233,  233,  372,  249,  250,  251,  244,  252,
      254,   60,   60,   60,   60,   60,  253,  255,  372,  256,
      257,  261,  245,  258,  259,  246,  260,  247,  248,  258,
      273,  372,  372,  129,  249,  372,  250,  251,  252,  254,
       60,   60,   60,   60,  372,  274,  253,  255,  256,  127,
      257,  261,  258,  259,  372,  260,  127,  372,  262,   68,

      273,  228,  228,  228,  183,  265,   68,  275,  263,  263,
      263,  263,  266,  231,  266,  274,  277,  267,  267,  267,
      267,  268,  268,  268,  276,  233,  233,  233,  233,  270,
      278,  279,  280,  281,  282,  284,  275,  283,  269,  271,
      285,  272,  272,  272,  272,  129,  277,  286,  287,  372,
      288,  289,  264,  276,  290,  291,  292,  372,  293,  278,
      279,  280,  281,  294,  282,  284,  283,  295,  269,  294,
      285,  297,  297,  297,  303,  303,  303,  286,  287,  288,
      289,  265,  372,  290,  372,  291,  292,  293,  298,  270,
      307,  304,  294,  267,  267,  267,  267,  295,  296,  271,

      270,  299,  299,  299,  299,  308,  372,  309,  310,  311,
      271,  305,  300,  300,  300,  301,  312,  270,  298,  307,
      313,  304,  314,  306,  306,  306,  306,  271,  315,  272,
      272,  272,  272,  316,  317,  308,  309,  310,  311,  318,
      372,  319,  320,  322,  321,  312,  323,  324,  372,  372,
      313,  372,  314,  334,  372,  372,  372,  372,  315,  372,
      335,  372,  316,  317,  372,  372,  372,  270,  372,  318,
      319,  320,  322,   70,  321,  323,  324,  271,  270,  325,
      325,  325,  301,  334,  270,  330,  330,  330,  271,  335,
      299,  299,  299,  299,  271,  270,  300,  300,  300,  301,

      336,  270,  331,  372,  372,  271,  372,  301,  301,  301,
      301,  271,  270,  327,  327,  327,  327,  337,  338,  372,
      339,  340,  271,  332,  328,  328,  328,  301,  341,  336,
      342,  345,  331,  271,   70,  333,  333,  333,  333,  346,
       70,  343,  344,  347,  357,  369,  337,  358,  338,  339,
      340,   70,  270,  372,  359,  372,  372,  341,  372,  372,
      342,  345,  271,  372,  325,  325,  325,  301,   70,  346,
      343,  344,  270,  347,  357,  369,  358,  372,  270,  129,
      372,  372,  271,  359,  348,  348,  348,  348,  271,  270,
      328,  328,  328,  301,  360,  361,  362,  332,  368,  271,

      372,  350,  350,  350,  350,  372,  332,  271,   70,  352,
      352,  352,  353,  355,  355,  355,  271,  372,  333,  333,
      333,  333,  372,  360,  361,  362,  332,  368,  372,  372,
      356,  372,  372,  372,   70,  372,  271,  332,  352,  352,
      352,  353,  372,  372,  332,  351,  372,  271,  372,  353,
      353,  353,  353,  129,  271,  332,  364,  364,  364,  364,
      356,  332,  129,  372,  372,  271,  372,  366,  366,  366,
      353,  271,  372,  366,  366,  366,  353,  332,  372,  372,
      372,  372,  129,  372,  372,  372,  372,  271,  372,  370,
      370,  370,  370,  129,  372,  372,  372,  372,  372,  372,

      365,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  129,  372,  372,  372,  372,  372,  129,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  371,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   60,  372,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       83,   83,   83,   83,   83,   83,   83,  111,  111,  372,
      372,  111,  111,  111,  111,  111,  114,  372,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,   53,
       53,   53,   53,   53,  372,   53,   60,   60,   60,  372,

      372,   60,  372,  372,  372,   60,  372,   60,  177,  372,
      177,  372,  177,  177,  177,  372,  372,  372,  177,   60,
       60,   60,   60,   60,  372,   60,  184,  184,  184,  372,
      372,  372,  184,  225,  372,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  229,  229,  229,  372,
      372,  372,  229,  302,  302,  302,  372,  372,  372,  302,
      326,  326,  326,  372,  372,  372,  326,  329,  329,  329,
      372,  372,  372,  329,  354,  354,  354,  372,  372,  372,
      354,  367,  367,  367,  372,  372,  372,  367,    5,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,

      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372
    } ;

static const flex_int16_t yy_chk[1374] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    7,    8,    8,    7,   10,   13,
       23,   10,   13,   17,   26,  371,   25,   10,   29,   18,

       10,   10,   10,   49,   49,   17,   17,   17,   17,   18,
       25,   18,   18,   18,   18,   20,   20,   10,  365,   23,
       20,   20,   33,   20,   26,   20,   25,   47,   29,   30,
       47,   28,   20,   20,   20,   20,   31,   32,   35,   25,
       10,   10,   38,   28,   27,   10,   34,   10,   27,   39,
      363,   33,   10,   27,   27,   18,   10,   27,   10,   30,
       10,   28,  351,   34,   84,   36,   31,   32,   35,   86,
       37,   38,   28,   36,   27,   88,   34,   27,   37,   39,
       42,  349,   27,   27,   50,   50,   27,   60,   42,  348,
       60,   20,   34,   84,   91,   36,  113,  113,   86,   55,

       37,  121,  121,   36,  327,   88,  131,   56,   37,   55,
       42,   55,   55,   55,   55,   57,  131,   56,   42,   56,
       56,   56,   56,   92,   91,   57,   68,   57,   57,   57,
       57,   61,   61,   61,   65,   65,   65,   97,   68,   68,
       68,   68,  172,  172,   66,   67,   67,   67,   61,  180,
       94,   65,  180,   92,   66,   55,   66,   66,   66,   66,
       87,  264,   67,   56,   85,  227,   85,   97,   96,   99,
      187,   57,   58,   58,   58,   58,   87,   98,   61,   94,
       85,   65,   58,   58,   58,   58,   58,   58,  178,   69,
       87,   89,   67,   90,   85,   93,   85,   96,   99,   69,

       66,   69,   69,   69,   69,   87,   93,   98,   89,   85,
       90,   95,   58,   58,   58,   58,   58,   58,  100,  102,
      101,   89,  103,   90,  102,   93,  101,   95,  104,  105,
      106,  107,  175,  108,  110,   93,  142,   89,  136,   90,
      132,   95,  124,  124,  124,   69,  129,  100,  111,  102,
      101,  103,  137,   78,  102,  101,   95,  104,  105,  106,
      115,  107,  108,  110,  139,  142,  116,   76,  136,  141,
      115,  143,  115,  115,  115,  115,  116,  117,  116,  116,
      116,  116,  137,  118,  173,  173,   74,  117,   70,  117,
      117,  117,  117,  118,  139,  118,  118,  118,  118,  141,

      120,  143,  144,   48,  122,  145,  123,  122,  146,  123,
      120,   46,  120,  120,  120,  120,  115,  122,  122,  123,
      123,  149,  116,   44,   41,  127,  127,  127,  147,  148,
       19,  125,  144,  117,  225,  145,   16,  225,  146,  118,
      119,  125,  127,  125,  125,  125,  125,  150,   15,  152,
      119,  149,  119,  119,  119,  119,  120,  147,  148,  153,
      140,  128,  119,  119,  119,  119,  119,  119,  130,  140,
      140,  128,  127,  128,  128,  128,  128,  150,  130,  152,
      130,  130,  130,  130,  138,  154,  157,  125,  138,  153,
      140,  155,  119,  119,  119,  119,  119,  119,  140,  140,

      156,  158,  159,   12,  160,  161,    9,  162,  164,  165,
      166,    5,  167,  168,  138,  154,  157,  128,  138,  169,
      155,  170,    4,  189,  130,  192,    3,    0,    0,  156,
      194,  158,  159,  160,  190,  161,  162,  164,  165,  193,
      166,  167,  168,  174,  195,    0,    0,  179,    0,  169,
      179,  170,  189,  174,  192,  174,  174,  174,  174,  194,
      179,  179,  182,    0,  190,  196,  197,    0,  198,  193,
      183,    0,  182,  195,  182,  182,  182,  182,  184,    0,
      183,    0,  183,  183,  183,  183,    0,  199,  184,    0,
      184,  184,  184,  184,    0,  196,  197,  198,    0,  174,

      181,  181,    0,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  199,  185,  182,  200,
      181,  181,  181,  181,  181,  181,  183,  185,  188,  185,
      185,  185,  185,  201,  184,  188,  202,  188,  203,  204,
      188,  188,  188,  188,    0,  205,  206,  207,  200,  208,
      211,  181,  181,  181,  181,  181,  210,  215,    0,  216,
      218,  223,  201,  220,  221,  202,  222,  203,  204,  224,
      235,    0,    0,  185,  205,    0,  206,  207,  208,  211,
      181,  181,  181,  181,    0,  236,  210,  215,  216,  228,
      218,  223,  220,  221,    0,  222,  229,    0,  224,  228,

      235,  228,  228,  228,  228,  230,  229,  237,  229,  229,
      229,  229,  230,  232,  230,  236,  239,  230,  230,  230,
      230,  231,  231,  231,  238,  232,  232,  232,  232,  233,
      240,  241,  242,  243,  244,  246,  237,  245,  231,  233,
      247,  233,  233,  233,  233,  228,  239,  248,  249,    0,
      250,  251,  229,  238,  254,  255,  256,    0,  257,  240,
      241,  242,  243,  258,  244,  246,  245,  261,  231,  262,
      247,  265,  265,  265,  270,  270,  270,  248,  249,  250,
      251,  266,    0,  254,    0,  255,  256,  257,  265,  267,
      273,  270,  258,  266,  266,  266,  266,  261,  262,  267,

      268,  267,  267,  267,  267,  275,    0,  276,  277,  278,
      268,  271,  268,  268,  268,  268,  279,  272,  265,  273,
      280,  270,  281,  271,  271,  271,  271,  272,  282,  272,
      272,  272,  272,  285,  286,  275,  276,  277,  278,  287,
        0,  288,  289,  291,  290,  279,  292,  295,    0,    0,
      280,    0,  281,  307,    0,    0,    0,    0,  282,    0,
      308,    0,  285,  286,    0,    0,    0,  297,    0,  287,
      288,  289,  291,  272,  290,  292,  295,  297,  299,  297,
      297,  297,  297,  307,  300,  305,  305,  305,  299,  308,
      299,  299,  299,  299,  300,  301,  300,  300,  300,  300,

      309,  302,  305,    0,    0,  301,    0,  301,  301,  301,
      301,  302,  303,  302,  302,  302,  302,  310,  311,    0,
      313,  315,  303,  306,  303,  303,  303,  303,  316,  309,
      317,  322,  305,  306,  299,  306,  306,  306,  306,  323,
      300,  318,  321,  324,  337,  359,  310,  338,  311,  313,
      315,  301,  325,    0,  341,    0,    0,  316,    0,    0,
      317,  322,  325,    0,  325,  325,  325,  325,  303,  323,
      318,  321,  326,  324,  337,  359,  338,    0,  328,  306,
        0,    0,  326,  341,  326,  326,  326,  326,  328,  329,
      328,  328,  328,  328,  343,  345,  347,  330,  357,  329,

        0,  329,  329,  329,  329,    0,  333,  330,  325,  330,
      330,  330,  330,  332,  332,  332,  333,    0,  333,  333,
      333,  333,    0,  343,  345,  347,  352,  357,    0,    0,
      332,    0,    0,    0,  328,    0,  352,  353,  352,  352,
      352,  352,    0,    0,  354,  329,    0,  353,    0,  353,
      353,  353,  353,  330,  354,  355,  354,  354,  354,  354,
      332,  366,  333,    0,    0,  355,    0,  355,  355,  355,
      355,  366,    0,  366,  366,  366,  366,  367,    0,    0,
        0,    0,  352,    0,    0,    0,    0,  367,    0,  367,
      367,  367,  367,  353,    0,    0,    0,    0,    0,    0,

      354,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  355,    0,    0,    0,    0,    0,  366,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  367,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  374,    0,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      375,  375,  375,  375,  375,  375,  375,  376,  376,    0,
        0,  376,  376,  376,  376,  376,  377,    0,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  378,
      378,  378,  378,  378,    0,  378,  379,  379,  379,    0,

        0,  379,    0,    0,    0,  379,    0,  379,  380,    0,
      380,    0,  380,  380,  380,    0,    0,    0,  380,  381,
      381,  381,  381,  381,    0,  381,  382,  382,  382,    0,
        0,    0,  382,  383,    0,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  384,  384,  384,    0,
        0,    0,  384,  385,  385,  385,    0,    0,    0,  385,
      386,  386,  386,    0,    0,    0,  386,  387,  387,  387,
        0,    0,    0,  387,  388,  388,  388,    0,    0,    0,
      388,  389,  389,  389,    0,    0,    0,  389,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,

      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[83] =
    {   0,
0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "mini.l"
#line 4 "mini.l"
#include <stdio.h>
#include "mini.tab.h"
#line 902 "lex.yy.c"

#line 904 "lex.yy.c"

#define INITIAL 0
#define COMENTARIO 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 29 "mini.l"


#line 1125 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 373 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1289 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 31 "mini.l"
BEGIN COMENTARIO;
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 32 "mini.l"
;
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 33 "mini.l"
BEGIN 0;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 35 "mini.l"
;
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 37 "mini.l"
;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 39 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(ARRAY);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 40 "mini.l"
printf("linea %d, operador tamano: %s\n", yylineno, yytext);return(TAMANO);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 41 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(CABECERA);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 42 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(CADA);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 43 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(CADENA);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 44 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(CARACTER);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 45 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(CONJUNTO);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 46 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(CONSTANTES);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 47 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(CONTINUAR);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 48 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(DE);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 49 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(DEFECTO);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 50 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(DEVOLVER);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 51 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(EJECUTA);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 52 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(ENCAMBIO);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 53 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(ENTERO);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 54 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(ES);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 55 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(ESCAPE);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 56 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(ESTRUCTURA);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 57 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(ETIQUETA);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 58 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(EXCEPCION);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 59 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(FICHERO);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 60 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(FIN);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 61 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(FUNCION);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 62 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(HACER);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 63 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(HASH);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 64 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(LANZA);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 65 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(MIENTRAS);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 66 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(NADA);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 67 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(OTRA);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 68 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(PARA);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 69 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(PRINCIPIO);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 70 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(PROGRAMA);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 71 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(REAL);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 72 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(REF);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 73 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(SALTAR);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 74 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(SI);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 75 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(SINO);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 76 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(TIPOS);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 77 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(UNION);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 78 "mini.l"
printf("linea %d, palabra reservada: %s\n", yylineno, yytext);return(VARIABLES);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 82 "mini.l"
{ printf("linea %d, operador aritmetico: %s\n", yylineno ,yytext);return POTENCIA;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 83 "mini.l"
{ printf("linea %d, operador relacional: %s\n", yylineno ,yytext);return EQ;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 84 "mini.l"
{ printf("linea %d, operador relacional: %s\n", yylineno ,yytext);return NEQ;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 85 "mini.l"
{ printf("linea %d, operador logico AND: %s\n", yylineno ,yytext);return AND;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 86 "mini.l"
{ printf("linea %d, operador logico OR: %s\n", yylineno ,yytext);return OR;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 87 "mini.l"
{ printf("linea %d, flecha derecha: %s\n", yylineno, yytext);return FLECHA_DCHA;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 88 "mini.l"
{ printf("linea %d, flecha izquierda: %s\n", yylineno, yytext);return FLECHA_IZDA;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 89 "mini.l"
{ printf("linea %d, operador: %s\n", yylineno, yytext);return GE;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 90 "mini.l"
{ printf("linea %d, operador: %s\n", yylineno, yytext);return LE;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 91 "mini.l"
{ printf("linea %d, operador asignacion modulo: %s\n", yylineno, yytext);return MOD_ASIG;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 92 "mini.l"
{ printf("linea %d, operador asignacion OR: %s\n", yylineno, yytext);return OR_ASIG;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 93 "mini.l"
{ printf("linea %d, operador indireccion: %s\n", yylineno, yytext);return INDIRECCION;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 94 "mini.l"
{ printf("linea %d, operador asignacion suma: %s\n", yylineno, yytext);return SUMA_ASIG;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 95 "mini.l"
{ printf("linea %d, operador: %s\n", yylineno, yytext);return FI_ASIG;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 96 "mini.l"
{ printf("linea %d, operador asignacion potencia: %s\n", yylineno, yytext);return POT_ASIG;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 97 "mini.l"
{ printf("linea %d, operador asignacion resta: %s\n", yylineno, yytext);return RESTA_ASIG;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 98 "mini.l"
{ printf("linea %d, operador: %s\n", yylineno, yytext);return FD_ASIG;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 99 "mini.l"
{ printf("linea %d, operador asignacion producto: %s\n", yylineno, yytext);return MULT_ASIG;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 100 "mini.l"
{ printf("linea %d, operador asignacion AND: %s\n", yylineno, yytext);return AND_ASIG;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 101 "mini.l"
{ printf("linea %d, operador asignacion division: %s\n", yylineno, yytext);return DIV_ASIG;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 102 "mini.l"
{ printf("linea %d, operador asignacion XOR: %s\n", yylineno, yytext);return XOR_ASIG;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 103 "mini.l"
{ printf("linea %d, operador de asignacion: %s\n", yylineno ,yytext);return yytext[0];}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 105 "mini.l"
{printf("linea %d, constante entera: %s\n", yylineno, yytext);return CTC_ENTERA;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 106 "mini.l"
{printf("linea %d, constante real: %s\n", yylineno, yytext);return CTC_REAL;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 107 "mini.l"
{printf("linea %d, constante con mantisa y/o exponente: %s\n", yylineno, yytext);return CTC_REAL;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 108 "mini.l"
{ printf("linea %d, operador aritmetico: %s\n", yylineno ,yytext);return yytext[0];}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 109 "mini.l"
{ printf("linea %d, operador de bit: %s\n", yylineno ,yytext);return yytext[0];}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 110 "mini.l"
{ printf("linea %d, operador relacional: %s\n", yylineno ,yytext);return yytext[0];}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 111 "mini.l"
{ printf("linea %d, operador logico: %s\n", yylineno ,yytext);return yytext[0];}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 112 "mini.l"
{ printf("linea %d, operador de acceso: %s\n", yylineno ,yytext);return yytext[0];}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 113 "mini.l"
{ printf("linea %d, delimitador: %s\n", yylineno ,yytext);return yytext[0];}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 114 "mini.l"
{ printf("linea %d, identificador: %s\n", yylineno ,yytext);return IDENTIFICADOR;} 
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 115 "mini.l"
{ printf("linea %d, ruta: %s\n", yylineno, yytext);return RUTA;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 116 "mini.l"
{printf("linea %d, caracter: %s\n", yylineno, yytext); return CTC_CARACTER;}
	YY_BREAK
case 80:
/* rule 80 can match eol */
YY_RULE_SETUP
#line 117 "mini.l"
{ printf("linea %d, cadena de caracteres: %s\n", yylineno ,yytext);return CTC_CADENA;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 119 "mini.l"
printf("linea %d,ERROR: %s\n",yylineno,yytext);
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 121 "mini.l"
ECHO;
	YY_BREAK
#line 1606 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMENTARIO):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 373 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 373 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 372);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 121 "mini.l"





